### ISSUE TITLE
reveal-bid instruction not showing correct bid amounts

### ISSUE THREAD

**Issue by jadster** [ethers-io/ethers-ens#10]
(minor inconsistency)

I made two bids for the same name with differing bid amounts. First 0.01, second 0.031. 

When the time came to reveal I got two "revealBid(" instructions, but both of them with the amount of my second bid, which was higher: 0.031.

![image](https://user-images.githubusercontent.com/22859910/27259423-71dcfa16-5413-11e7-8181-056aa4f372da.png)

**Comment by ricmoo** [comment]
Ack! You are correct. I am busy through-out the day, but should have a chance tonight to fix that.

Thanks!
RicMoo

**Comment by jadster** [comment]
no hurry. the "--nonce" flag would be higher priority for me :-)

**Comment by ricmoo** [comment]
Sorry, catching up on old issues.

The `--nonce` flag is supported and since bidding is no longer used, those features have been phased out.

Anyways, if there are any other issues, please feel free to re-open on the [main repository](https://github.com/ethers-io/ethers.js) that this is now managed in. :)
