### ISSUE TITLE
ignore overrides all commands placed later

### ISSUE THREAD

**Issue by jadster** [ethers-io/ethers-ens#11]
For a single name I had placed in this sequence of commands:

1. *watch*
2. *ignore*
3. *start-auction*
4. *bid*

The *ignore* command had overridden the following commands. Which means the name did not show up in *scan-log* as *revealBid()".
Not sure if that's by design, but I'd prefer later commands such as *start-auction* or *bid* to override the *ignore*... Only an *ignore* that was placed as the latest command should override all other commands.

**Comment by ricmoo** [comment]
You are quite correct, it makes a lot of sense for bid, start-auction and finalize-auction to add a watch entry to the end-log.

I will fix this soon.

**Comment by ricmoo** [comment]
Sorry catching up on old issues...

There is no longer a "watch"-like feature, since the commit-reveal is only 1 minute long. It was originally done that way because 5 days was a long time to keep track of everything,  but it was a bit cumbersome, having to keep log files around and whatnot...

So, closing this now. :)
